### ISSUE TITLE
[新群]: 

### ISSUE THREAD

**Issue by Grigya** [SherkeyXD/XMU-Groups#3]
### 群号

853107180

### 群名称

现代视觉文化研究社人际关系类分部 xmu.ver

### 群聊内容标签

galgame

### 加群链接

http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=VtZ94msCbQB4qtZHIB9-UUY0eVBisv3R&authKey=USsWh%2BlaaYqAgtyk2Z1a%2B6UqigwM2yl72Cr4Zf0eUpCzLzf2AwVLJkkJqMgKe42z&noverify=0&group_code=853107180

### 有什么想说的吗

我是柚子厨，退群了😭(开个玩笑其实并没有🥴)
欢迎喜欢galgame的🦐带同好

**Comment by SherkeyXD** [comment]
#4
